name: Update Subscription
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Subscription url'
        type: string
        required: false
jobs:
  update_reboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          

      - name: Update Subcription
        env:
          SUB_URL: ${{ github.event.inputs.subscription }}
          SEC_URL: ${{ secrets.SUB_URL }}
        run: |
          if [ $SUB_URL ]; then curl -o new.yaml $SUB_URL; else curl -o new.yaml $SEC_URL; fi
          python merge.py
      

      - name: Package
        run: bash ./package.sh

      - uses: actions/checkout@v3
        with:
          repository: 'peanut996/bucket'
          path: bucket
          token: ${{ secrets.GH_TOKEN }}

      - name: Push
        run: |
          mv clash-v1.5.0.tar.gz install_clash.sh bucket
          cd bucket
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -f clash-v1.5.0.tar.gz install_clash.sh
          git commit -m "update bucket"
          git push origin
  
      - name: Reboot clash
        uses: matheusvanzan/sshpass-action@v2
        with:
         host: ${{ secrets.HOST }}
         port: ${{ secrets.PORT }}
         user: ${{ secrets.USER }}
         pass: ${{ secrets.PASS }}
         run: ${{ secrets.CMD }}
